/*  state.course Actions  */
export const COURSE_FETCH = {
  REQUEST: 'COURSE_FETCH_REQUEST',
  RECEIVE: 'COURSE_FETCH_RECEIVE',
  ERROR: 'COURSE_FETCH_ERROR'
};

/*  state.filter Actions  */
export const FILTER_OPTIONS_FETCH = {
  REQUEST: 'FILTER_OPTIONS_FETCH_REQUEST',
  RECEIVE: 'FILTER_OPTIONS_FETCH_RECEIVE',
  ERROR: 'FILTER_OPTIONS_FETCH_ERROR'
};

export const FILTER_UPDATE = 'FILTER_UPDATE';
