export default [
  { name: 'Asian American Studies', code: 'AAS' },
  { name: 'Agricultural and Biological Engineering', code: 'ABE' },
  { name: 'Agricultural and Consumer Economics', code: 'ACE' },
  { name: 'Agricultural, Consumer and Environmental Sciences', code: 'ACES' },
  { name: 'Advertising', code: 'ADV' },
  { name: 'Air Force Aerospace Studies', code: 'AFAS' },
  { name: 'African American Studies', code: 'AFRO' },
  { name: 'Agricultural Communications', code: 'AGCM' },
  { name: 'Agricultural Education', code: 'AGED' },
  { name: 'Applied Health Sciences Courses', code: 'AHS' },
  { name: 'American Indian Studies', code: 'AIS' },
  { name: 'Animal Sciences', code: 'ANSC' },
  { name: 'Anthropology', code: 'ANTH' },
  { name: 'Arabic', code: 'ARAB' },
  { name: 'Architecture', code: 'ARCH' },
  { name: 'Art', code: 'ART' },
  { name: 'Art--Design', code: 'ARTD' },
  { name: 'Art--Education', code: 'ARTE' },
  { name: 'Art--Foundation', code: 'ARTF' },
  { name: 'Art--History', code: 'ARTH' },
  { name: 'Art--Studio', code: 'ARTS' },
  { name: 'Actuarial Science and Risk Management', code: 'ASRM' },
  { name: 'Asian Studies', code: 'ASST' },
  { name: 'Astronomy', code: 'ASTR' },
  { name: 'Atmospheric Sciences', code: 'ATMS' },
  { name: 'Business Administration', code: 'BADM' },
  { name: 'Basque', code: 'BASQ' },
  { name: 'Brain and Cognitive Science', code: 'BCOG' },
  { name: 'Bosnian-Croatian-Serbian', code: 'BCS' },
  { name: 'Accountancy', code: 'ACCY' },
  { name: 'Aerospace Engineering', code: 'AE' },
  { name: 'African Studies', code: 'AFST' },
  { name: 'Biochemistry', code: 'BIOC' },
  { name: 'Bioengineering', code: 'BIOE' },
  { name: 'Biology', code: 'BIOL' },
  { name: 'Biophysics', code: 'BIOP' },
  { name: 'Biomedical Sciences and Engineering', code: 'BSE' },
  { name: 'Comparative Biosciences', code: 'CB' },
  { name: 'Cell and Developmental Biology', code: 'CDB' },
  { name: 'Civil and Environmental Engineering', code: 'CEE' },
  { name: 'Chemical and Biomolecular Engineering', code: 'CHBE' },
  { name: 'Chemistry', code: 'CHEM' },
  { name: 'Chinese', code: 'CHIN' },
  { name: 'Community Health', code: 'CHLH' },
  { name: 'Campus Honors Program Courses', code: 'CHP' },
  { name: 'Curriculum and Instruction', code: 'CI' },
  { name: 'Business and Technical Writing', code: 'BTW' },
  { name: 'Classical Civilization', code: 'CLCV' },
  { name: 'Clinical Sciences and Engineering', code: 'CLE' },
  { name: 'Business', code: 'BUS' },
  { name: 'Crop Sciences', code: 'CPSC' },
  { name: 'Computer Science', code: 'CS' },
  { name: 'Computational Science and Engineering', code: 'CSE' },
  { name: 'Creative Writing', code: 'CW' },
  { name: 'Comparative and World Literature', code: 'CWL' },
  { name: 'Czech', code: 'CZCH' },
  { name: 'Dance', code: 'DANC' },
  { name: 'East Asian Language and Culture', code: 'EALC' },
  { name: 'Electrical and Computer Engineering', code: 'ECE' },
  { name: 'Economics', code: 'ECON' },
  { name: 'Communication', code: 'CMN' },
  { name: 'Committee on Inst Cooperation', code: 'CIC' },
  { name: 'Educational Practice', code: 'EDPR' },
  { name: 'Engineering', code: 'ENG' },
  { name: 'Engineering Honors', code: 'ENGH' },
  { name: 'English', code: 'ENGL' },
  { name: 'Environmental Sustainability', code: 'ENSU' },
  { name: 'Entomology', code: 'ENT' },
  { name: 'Environmental Studies', code: 'ENVS' },
  { name: 'Educational Organization and Leadership', code: 'EOL' },
  { name: 'Education Policy, Organization and Leadership', code: 'EPOL' },
  { name: 'English as an International Language', code: 'EIL' },
  { name: 'Educational Policy Studies', code: 'EPS' },
  { name: 'Earth, Society, and Environment', code: 'ESE' },
  { name: 'English as a Second Language', code: 'ESL' },
  { name: 'European Union Studies', code: 'EURO' },
  { name: 'Fine and Applied Arts', code: 'FAA' },
  { name: 'Finance', code: 'FIN' },
  { name: 'Foreign Language Teacher Education', code: 'FLTE' },
  { name: 'French', code: 'FR' },
  { name: 'Food Science and Human Nutrition', code: 'FSHN' },
  { name: 'Graduate College', code: 'GC' },
  { name: 'Grand Challenge Learning', code: 'GCL' },
  { name: 'Geography', code: 'GEOG' },
  { name: 'Geology', code: 'GEOL' },
  { name: 'German', code: 'GER' },
  { name: 'Global Studies', code: 'GLBL' },
  { name: 'Germanic', code: 'GMC' },
  { name: 'Greek', code: 'GRK' },
  { name: 'Modern Greek', code: 'GRKM' },
  { name: 'General Studies', code: 'GS' },
  { name: "Gender and Women's Studies", code: 'GWS' },
  { name: 'Human Development and Family Studies', code: 'HDFS' },
  { name: 'Hebrew, Modern and Classical', code: 'HEBR' },
  { name: 'History', code: 'HIST' },
  { name: 'Hindi', code: 'HNDI' },
  { name: 'Horticulture', code: 'HORT' },
  { name: 'Human Resource Development', code: 'HRD' },
  { name: 'Humanities Courses', code: 'HUM' },
  { name: 'Integrative Biology', code: 'IB' },
  { name: 'Industrial Engineering', code: 'IE' },
  { name: 'i-Health Program', code: 'IHLT' },
  { name: 'Informatics', code: 'INFO' },
  { name: 'Information Sciences', code: 'IS' },
  { name: 'Italian', code: 'ITAL' },
  { name: 'Japanese', code: 'JAPN' },
  { name: 'Journalism', code: 'JOUR' },
  { name: 'Jewish Studies', code: 'JS' },
  { name: 'Kinesiology', code: 'KIN' },
  { name: 'Korean', code: 'KOR' },
  { name: 'Landscape Architecture', code: 'LA' },
  { name: 'Liberal Arts and Sciences', code: 'LAS' },
  { name: 'Latin American and Caribbean Studies', code: 'LAST' },
  { name: 'Latin', code: 'LAT' },
  { name: 'Law', code: 'LAW' },
  { name: 'Labor and Employment Relations', code: 'LER' },
  { name: 'Linguistics', code: 'LING' },
  { name: 'Latina/Latino Studies', code: 'LLS' },
  { name: 'Media and Cinema Studies', code: 'MACS' },
  { name: 'Mathematics', code: 'MATH' },
  { name: 'Regular MBA Program Administration', code: 'MBA' },
  { name: 'Molecular and Cell Biology', code: 'MCB' },
  { name: 'Media', code: 'MDIA' },
  { name: 'Medieval Studies', code: 'MDVL' },
  { name: 'Mechanical Engineering', code: 'ME' },
  { name: 'Microbiology', code: 'MICR' },
  { name: 'Military Science', code: 'MILS' },
  { name: 'Molecular and Integrative Physiology', code: 'MIP' },
  { name: 'Materials Science and Engineering', code: 'MSE' },
  { name: 'Music', code: 'MUS' },
  { name: 'Museum Studies', code: 'MUSE' },
  { name: 'Neuroscience', code: 'NEUR' },
  { name: 'Nuclear, Plasma, and Radiological Engineering', code: 'NPRE' },
  { name: 'Natural Resources and Environmental Sciences', code: 'NRES' },
  { name: 'Naval Science', code: 'NS' },
  { name: 'Nutritional Sciences', code: 'NUTR' },
  { name: 'Pathobiology', code: 'PATH' },
  { name: 'Plant Biology', code: 'PBIO' },
  { name: 'Persian', code: 'PERS' },
  { name: 'Philosophy', code: 'PHIL' },
  { name: 'Physics', code: 'PHYS' },
  { name: 'Plant Pathology', code: 'PLPA' },
  { name: 'Polish', code: 'POL' },
  { name: 'Portuguese', code: 'PORT' },
  { name: 'Political Science', code: 'PS' },
  { name: "Professional Science Master's Program", code: 'PSM' },
  { name: 'Psychology', code: 'PSYC' },
  { name: 'Russian, East European and Eurasian Studies', code: 'REES' },
  { name: 'Rehabilitation Counseling', code: 'REHB' },
  { name: 'Religion', code: 'REL' },
  { name: 'Rhetoric and Composition', code: 'RHET' },
  { name: 'Romance Linguistics', code: 'RMLG' },
  { name: 'Education', code: 'EDUC' },
  { name: 'Recreation, Sport, and Tourism', code: 'RST' },
  { name: 'South Asian and Middle Eastern Studies', code: 'SAME' },
  { name: 'Strategic Brand Communication', code: 'SBC' },
  { name: 'Scandinavian', code: 'SCAN' },
  { name: 'Systems Engineering and Design', code: 'SE' },
  { name: 'Russian', code: 'RUSS' },
  { name: 'Speech and Hearing Science', code: 'SHS' },
  { name: 'Literatures, Cultures, and Linguistics', code: 'SLCL' },
  { name: 'Second Language Studies', code: 'SLS' },
  { name: 'Sociology', code: 'SOC' },
  { name: 'Social Work', code: 'SOCW' },
  { name: 'Spanish', code: 'SPAN' },
  { name: 'Special Education', code: 'SPED' },
  { name: 'Statistics', code: 'STAT' },
  { name: 'Swahili', code: 'SWAH' },
  { name: 'Educational Psychology', code: 'EPSY' },
  { name: 'Theoretical and Applied Mechanics', code: 'TAM' },
  { name: 'Theatre', code: 'THEA' },
  { name: 'Technology and Management Courses', code: 'TMGT' },
  { name: 'Translation Studies', code: 'TRST' },
  { name: 'Technical Systems Management', code: 'TSM' },
  { name: 'Turkish', code: 'TURK' },
  { name: 'Ukrainian', code: 'UKR' },
  { name: 'Urban and Regional Planning', code: 'UP' },
  { name: 'Veterinary Clinical Medicine', code: 'VCM' },
  { name: 'Veterinary Medicine Courses', code: 'VM' },
  { name: 'Women and Gender in Global Perspectives Program', code: 'WGGP' },
  { name: 'Wolof', code: 'WLOF' },
  { name: 'Writing Studies', code: 'WRIT' },
  { name: 'Yiddish', code: 'YDSH' },
  { name: 'Slavic', code: 'SLAV' },
  { name: 'Technology Entrepreneurship', code: 'TE' },
  { name: 'Center for Advanced Study', code: 'CAS' }
];
